spring:
  application:
    name: "mini-quotation-user-service"

  datasource:
    url: jdbc:mysql://localhost:3306/mini_quotation_user_db
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: info

server:
  port: ${PORT:0}

Eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8080/eureka"
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}